#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use Readonly;
use Template;

Readonly my @IMAGE_NAMES => qw(
	build-agent-debian
	build-agent-fedora
	build-agent-freebsd
	build-agent-ipxtester
	build-agent-windows
	build-cluster-manager
);

my $tt = Template->new(
	INCLUDE_PATH => $FindBin::Bin,
);

{
	open(my $workflow, ">", "$FindBin::Bin/../.github/workflows/build-images.yaml")
		or die "$FindBin::Bin/../.github/workflows/build-images.yaml: $!\n";
	
	print {$workflow} "# This file was generated by update-workflows.pl - do not edit it directly!\n\n";
	
	$tt->process(
		"build-images.yaml.tt",
		{ image_names => \@IMAGE_NAMES },
		$workflow)
		
		or die $tt->error(), "\n";
	
	close($workflow);
}
