#!/bin/bash

IMAGES="\
	build-agent-debian \
	build-agent-fedora \
	build-agent-freebsd \
	build-agent-ipxtester \
	build-agent-windows \
	build-cluster-manager \
"

tmpfile=$(mktemp)

echo "# This file was generated by update-workflows.sh - do not edit it directly!" > .github/workflows/build-images.yaml
echo "" >> .github/workflows/build-images.yaml

cat workflow-templates/build-images-head.yaml >> .github/workflows/build-images.yaml

for image in $IMAGES
do
	cat workflow-templates/build-images-job.yaml > "$tmpfile"
	
	sed -i -e "s/BUILD_IMAGES_IMAGE_NAME/${image}/g" "$tmpfile"
	
	cat "$tmpfile" >> .github/workflows/build-images.yaml
done

rm "$tmpfile"
